# Generated by Django 2.2.1 on 2024-05-08 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pims', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='supplier_id',
            new_name='supplier',
        ),
        migrations.RenameField(
            model_name='productimages',
            old_name='product_id',
            new_name='product',
        ),
    ]
