# Generated by Django 4.2.13 on 2024-05-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pims', '0002_auto_20240508_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.JSONField(blank=True, default=list, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='ProductImages',
        ),
    ]
