# Generated by Django 4.2.13 on 2024-05-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pims', '0003_product_images_alter_product_stock_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='contact_info',
            field=models.TextField(max_length=50),
        ),
    ]
