# Generated by Django 4.2.13 on 2024-05-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pims', '0004_alter_supplier_contact_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
